# Generated by Django 4.1.5 on 2023-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'In stock'), ('Out Of stock', 'Out Of Stock')], max_length=100, null=True),
        ),
    ]
